// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRxIZep8xl4WLmH9DfyEhMACWSZBHIW1Y',
    appId: '1:196173659226:web:2b2c83a892cf51c1db2c63',
    messagingSenderId: '196173659226',
    projectId: 'flash-chat-27164',
    authDomain: 'flash-chat-27164.firebaseapp.com',
    storageBucket: 'flash-chat-27164.appspot.com',
    measurementId: 'G-LCZ5B3DZCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrvYkU5OjOuvKOIKHoe9v_0MeFIQSROnE',
    appId: '1:196173659226:android:b8b086f1cf59607edb2c63',
    messagingSenderId: '196173659226',
    projectId: 'flash-chat-27164',
    storageBucket: 'flash-chat-27164.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_U1wfeVgTyHEGahqsOc9Xv2VaSxywIzE',
    appId: '1:196173659226:ios:f0ef727cd49c7939db2c63',
    messagingSenderId: '196173659226',
    projectId: 'flash-chat-27164',
    storageBucket: 'flash-chat-27164.appspot.com',
    iosClientId: '196173659226-plmcta6nkrlsa7tspg9phsokcqpr1c3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_U1wfeVgTyHEGahqsOc9Xv2VaSxywIzE',
    appId: '1:196173659226:ios:f0ef727cd49c7939db2c63',
    messagingSenderId: '196173659226',
    projectId: 'flash-chat-27164',
    storageBucket: 'flash-chat-27164.appspot.com',
    iosClientId: '196173659226-plmcta6nkrlsa7tspg9phsokcqpr1c3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashchat',
  );
}
